name: Build Fabric Mod

on:
  push:
    branches: [ "main", "master" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.11.1'

      - name: Build Mod with Gradle
        run: gradle remapJar --no-daemon

      - name: Upload Remapped Mod Jar
        uses: actions/upload-artifact@v4
        with:
          name: pearl-indicator-jar
          path: build/libs/pearlindicator-1.0.0.jar

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: build/libs/pearlindicator-1.0.0.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
