name: Build Fabric Mod

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.11.1'

      - name: Build Mod
        run: gradle remapJar --no-daemon

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PearlIndicator-1.21.4
          path: build/libs/*[!sources].jar
